apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
    environment: production
    team: devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
        environment: production
        team: devsecops
    spec:
      securityContext:                # Pod-level security context
        runAsNonRoot: true
        runAsUser: 1001               # Ensure all containers in the pod run as non-root
      containers:
      - name: netflix-app
        image: wwdreda/netflixv3
        securityContext:
          allowPrivilegeEscalation: false # Disable privilege escalation
          capabilities:
            drop:
            - ALL                     # Drop all unnecessary capabilities
            add:                      # Add back only the required capabilities
            - CHOWN
            - SETGID
            - SETUID
            - NET_BIND_SERVICE
        ports:
        - containerPort: 80


