apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
    environment: production
    team: devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
        environment: production
        team: devsecops
    spec:
      securityContext:                # Pod-level security context
        runAsNonRoot: true            # Ensure all containers in the pod run as non-root
      containers:
      - name: netflix-app
        image: sreedhar8897/netflix:latest
        securityContext:              # Container-level security context
          allowPrivilegeEscalation: false # Disable privilege escalation
          runAsUser: 1000             # Specify a non-root user
          capabilities:
            drop:                     # Drop all unnecessary Linux capabilities
            - ALL
          readOnlyRootFilesystem: true # Enforce read-only root filesystem
        ports:
        - containerPort: 80

