apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: netflix-app
        image: sreedhar8897/netflix:latest
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false
