apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
    environment: production
    team: devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
        environment: production
        team: devsecops
    spec:
      containers:
      - name: netflix-app
        image: wwdreda/netflix:latest
        env:
        - name: VITE_APP_TMDB_V3_API_KEY
          valueFrom:
            secretKeyRef:
              name: tmdb-api-key
              key: VITE_APP_TMDB_V3_API_KEY
        securityContext:
          allowPrivilegeEscalation: false # Disable privilege escalation
          capabilities:
            drop:
            - ALL                     # Drop all unnecessary capabilities
            add:                      # Add back only the required capabilities
            - CHOWN
            - SETGID
            - SETUID
            - NET_BIND_SERVICE
          seccompProfile:                # Use the default seccomp profile
            type: RuntimeDefault
        ports:
        - containerPort: 80


