apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sallowedimageregistry
spec:
  crd:
    spec:
      names:
        kind: K8sAllowedImageRegistry
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sallowedimageregistry

        violation[{"msg": msg}] {
          input.review.kind.kind == "Pod"
          not startswith(input.review.object.spec.containers[_].image, "sreedhar8897/")
          msg := sprintf("Container image must originate from the approved registry 'sreedhar8897/': %s", [input.review.object.spec.containers[_].image])
        }
